### ISSUE TITLE
Unable to setup with Python3 under Debian testing

### ISSUE THREAD

**Issue by ngiger** [dribdat/dribdat#106]
I followed the instruction in the readme. And got the following error

<pre>
 python3 manage.py db init
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    from dribdat.app import init_app
  File "/opt/src/dribdat/dribdat/app.py", line 5, in <module>
    from dribdat import commands, public, user, admin
  File "/opt/src/dribdat/dribdat/public/__init__.py", line 3, in <module>
    from . import views, auth, api  # noqa
  File "/opt/src/dribdat/dribdat/public/views.py", line 7, in <module>
    from dribdat.user.models import User, Event, Project
  File "/opt/src/dribdat/dribdat/user/models.py", line 9, in <module>
    from dribdat.extensions import hashing
  File "/opt/src/dribdat/dribdat/extensions.py", line 6, in <module>
    from flask_oauth import OAuth
  File "/home/niklaus/.local/lib/python3.5/site-packages/flask_oauth.py", line 13, in <module>
    from urlparse import urljoin
ImportError: No module named 'urlparse'
</pre>

Tested on Librem Laptop, running a debian testing with Python 3.5.4 installed.

**Comment by ngiger** [comment]
Bug is known see https://github.com/mitsuhiko/flask-oauth/commit/c8e6e19a14616a74222f7f1ff1254d7d9a340e9b
But a release of flask-oauth 0.13 never came.

**Comment by loleg** [comment]
Fixed by using latest version of package from Git commit. Thanks @ngiger
