### ISSUE TITLE
Unable to login from Safari (Python 3)

### ISSUE THREAD

**Issue by loleg** [dribdat/dribdat#73]
On certain server configurations, a user of Safari browser was unable to login or register for an account. The server logs contain this message:

```
Exception on /login/ [GET]
Traceback (most recent call last):
  ...
  File "/srv/soda/dribdat/dribdat/public/auth.py", line 32, in login
 line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/srv/soda/dribdat/env/lib/python3.4/site-packages/flask_wtf/csrf.py", li
ne 134, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "/srv/soda/dribdat/env/lib/python3.4/site-packages/flask_wtf/csrf.py", li
ne 47, in generate_csrf
    setattr(g, field_name, s.dumps(session[field_name]))
  ...
  File "/usr/lib/python3.4/json/encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'daefd4f311284ca5ce9cf4503bfba12c55918eb0' is not JSON serializable
127.0.0.1 - - [23/Jan/2017 17:38:04] "GET /login/ HTTP/1.0" 500 -
```

This could be related to [this issue](http://stackoverflow.com/questions/27161631/safari-on-mobile-resets-csrf-token-in-flask-gae-session?rq=1).

This happens only when running Dribdat on Python 3, and is related to string conversion (Unicode from octet). 

Not sure why it only affects a specific browser, though.

**Comment by loleg** [comment]
Looks like this is a Python 3 compatibility issue with the [bcrypt](https://github.com/loleg/dribdat/blob/master/requirements/prod.txt#L43) library.

**Comment by loleg** [comment]
[bcrypt](https://github.com/pyca/bcrypt) has come a ways forward since 2017, and I haven't heard of any more such user complaints.
